### ISSUE TITLE
Some batch sizes lead to corrupted files

### ISSUE THREAD

**Issue by LoZio** [BitcoinRaven/CAMEbruteforcer#3]
I created several batches. Using size=25 the resulting files are not well formed and cannot be aired.
See
https://github.com/flipperdevices/flipperzero-firmware/issues/1540

(and not to open another issue since it's a trivial fix: zero fill the file number i.e. CAME_50_**00**3 to be easier to read/find)

**Comment by BitcoinRaven** [comment]
I noticed this problem a while ago, what happened the flipper keeps sending endlessly, I thought it was one time thing, let me check whats going on, and i will try your fix

**Comment by BitcoinRaven** [comment]
file name fixed
